### PR TITLE
icon examples added

### PR DESCRIPTION
**Pull request by wasim919**

### CODE REVIEW

**Review by Scientist-Ansh — COMMENTED** [review]
Can you please check your example file. I really dont understand what is going on there, youu have headings like grey, grey outline but nothing is changing in icon.

**Comment by iamcucusa** [comment]
Guys this is not correct, icons should be created at list with the CSS background property pointing to the svg.

**Comment by iamcucusa** [comment]
Could

**Comment by iamcucusa** [comment]
Closed because it is not doing what is expected. Other teams will add their icons themselves

**Pull request closed without merging**
