### PR TITLE
fix: added missing <section>

### PR DESCRIPTION
**Pull request by Zurina**

### CODE REVIEW

**Comment by iamcucusa** [comment]
Still have another tag to fix

teams/1/Contacts.html 294ms
teams/1/Dashboard.html 162ms
teams/1/LandingPage.html
[error] teams/1/LandingPage.html: SyntaxError: Unexpected closing tag "section". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (216:7)
[error]   214 |       </article>
[error]   215 |
[error] > 216 |       </section>
[error]       |       ^^^^^^^^^^
[error]   217 |
[error]   218 |       <section class="free-trial">
[error]   219 |         <h2>Start your free trial</h2>

**Comment by Zurina** [comment]
Are you sure? I believe I just fixed that

**Comment by iamcucusa** [comment]
Yeah, it is only a tag in LandingPage.html. I am checking locally your brach
image
image

**Comment by Zurina** [comment]
Now it should be fixed. It was apparently a missing article tag..

**Comment by iamcucusa** [comment]
Thanks

**Review by iamcucusa — APPROVED** [review]

**Pull request merged**
